reactiflux/reactibot

- features/commands.js
This content is borrowed from https://www.reactiflux.com/tips/, similarly to !ask.
> Add !ping command

- features/commands.js
Add !code/!gist command to tell people how to attach small or large blocks of code
> Add !code/!gist command

- features/MDN/index.js
- features/commands.js
- index.js
- package-lock.json
- package.json
!mdn command for the bot. Couple of things to notice, it tokenize the input and run a fuzzy search to find the nearest match so you can write `reduce` instead of `Array.prototype.reduce` to still get a result. However there are times at where you'll have to specify abit more to get the desired result, for ex - `forEach` might match to `Map.prototype.forEach` or `Array.prototype.forEach` so in that case it "might" be better to be abit more specific and say `Array forEach`.
> mdn command for reactibot

- features/stats.js
- index.js
- package-lock.json
- package.json
Also needs a new env variable! `AMPLITUDE_KEY`
> Add Amplitude event emitter

- features/commands.js
https://goshakkk.name/controlled-vs-uncontrolled-inputs-react/
> Add !inputs to explain uncontrolled vs controlled inputs

- package-lock.json
This simply commits changes from `npm audit fix` for 1 High vuln
> Audit npm packages

- features/commands.js
Since there is a very noticeable delay while it is fetching the article, also added a self-deleting fetching message.
> Fix mdn command

- index.js
> Add help status

- features/commands.js
This is an initial idea for adding codesandbox messaging to the `!code` command.
Please comment so we can improve this message and get it released 🙏
> Add codesandbox to code command

- .dockerignore
- .gitignore
- Dockerfile
- package.json
Beep boop, fat chance on me writing test plans.
> Add Dockerfile so we can run the bot in a container

- package.json
Reverts reactiflux/reactibot#35
> Revert "Pin discord.js version to commit"

- features/commands.js
Myself and others in the community have reviewed this github link and find it very helpful.  I think it could benefit the ecosystem and honestly at least a couple times a day a new Reactiflux-er is asking "What can I build?".  This is a helpful list, non opinionated and well documented with user stories etc.  I think it would be a benefit to the Reactiflux community.
-Mark "Elsewhere" Lynch
> Add !appIdeas to command bot.

- features/emojiMod.js
- index.js
https://discordjs.guide/popular-topics/partials.html#enabling-partials
Beep boop I'm a robot.
> Migrate to the new cache API for emoji mod

- Dockerfile
Required to fix errors with Discord.js due to an outdated Node version
> Upgrade to Node 12

- .github/workflows/main.yml
- src/features/commands.ts
- src/features/log.ts
- src/features/qna.ts
- src/index.ts
This will catch uncaught exceptions or promise rejections and log them out to a channel.
> Add better error logging

- src/features/commands.ts
> Add !cors command

- src/features/commands.ts
> Add !immutability command

- src/features/commands.ts
> Add !formatting command

- src/features/commands.ts
> Warn users when they try to ping here or everyone

- src/index.ts
I guess this is copy-paste's fault, but yeah, change from fetching the reaction twice to fetching the user then the reaction.
> Actually fetch the user

- package.json
- src/features/commands.ts
Adds links to my "React Rendering Behavior" and "When to use Redux" posts
> Add !render and !redux commands

- package-lock.json
- package.json
- src/features/scheduled-messages.ts
- src/index.ts
This PR introduces the ability to schedule messages using cron syntax.
To schedule a message you add an entry to `MESSAGE_SCHEDULE` with the following properties:
- The cron string
- An array of guilds. Inside each guild is its id and the ids of the channels to send to
- The message
> Message Scheduling

- src/features/commands.ts
This PR:
- Finally adds a "Redux vs Context"-specific help entry
> Add Redux vs Context entry

- src/features/commands.ts
- src/features/emojiMod.ts
I don't have my tokens on this computer but this should work.
> Warn messages that ping everyone

- src/features/autodelete-spam.ts
- src/index.ts
reference: https://discord.com/channels/102860784329052160/106168778013822976/882015438693892176
> log and autodelete msgs with here/everyone pings and spam keywords

- src/features/commands.ts
- src/helpers/misc.ts
Also removes cooldown from `@everyone` handler, and introduces `sleep()` helper
> Clean up "tsk tsk" messages 2 mins after sending

- .gitignore
- package-lock.json
- package.json
- src/features/jobs.ts
- src/features/stats.ts
* Update to discord.js@13.5.0 (closes #139)
* gitignore all .env files
* Skip reactibot messages when emitting metrics
* Avoid fetching partials when staff posts to `#job-board`
> Small fixes

- src/index.ts
This fixes all the issues I'm aware of! `!commands` are correctly responded to and metrics are correctly emitted. Closes #133
> Join every thread created

- src/features/autothread.ts
- src/features/scheduled-messages.ts
* Tune down idle thread closure from 6 hours to 12 hours
* Adjust frequency of some scheduled messages, and change copy for the one posted to #random
> Adjustments to new features

- package.json
- src/constants.ts
- src/features/autodelete-spam.ts
- src/features/commands.ts
- src/features/emojiMod.ts
- src/helpers/array.ts
- src/helpers/modLog.ts
- src/index.ts
- yarn.lock
* Don't ping channel members when an `@everyone` message is reported
* Refactor logic to remove duplicated code
* Automatically ban after 5 deduped warnings
> Fix mod log issues

- src/features/commands.ts
- src/helpers/discord.ts
#123 
For `isStaffAdmin` utility, I'm assuming the member has `ADMINISTRATOR` permission checked in one of their roles (Admin, Moderator).
Also @vcarl can you add me to the test server. my discord user is **banny`#2169**
> lock and unlock channel commands

- src/features/autodelete-spam.ts
I think it's safe enough to delete messages that contain spammy words and a url
> Auto delete messages that contain a url but don't tag everyone

- src/features/commands.ts
> Disable thread creation in locked channel

- .github/workflows/node.js.yml
- Dockerfile
- package.json
The build got into a bad spot, failing to complete in production. Separately, I think that PRs to `feature/actions` (which is hardcoded in the action workflow as a test branch that will run a complete deployment) may not be properly checking out the right branch. I didn't get the results I expected until I ssh'd into the reactibot server and checked out `feature/actions` there manually, even though the Action workflow specifies that it checks out the head of whatever branch is used
> Fix deployment

- .github/workflows/node.js.yml
- Dockerfile
- package.json
- src/index.ts
* Fix race condition in deployment
* Run on `push` event on `main` 
* Ensure devDeps aren't included in final image
* Log when bootstrap starts
> Small build optimizations

- src/features/scheduled-messages.ts
> change 'World' to 'Wordle' as originally intended

- src/features/jobs-moderation.ts
- The warnings posted by the bot in the job-board channel is now sent in
a thread. If the thread creation fails the same warning is sent as a
reply to the message in question
> Thread/Replies for warnings in job-board

- src/helpers/discord.ts
- src/helpers/modLog.ts
> Escape pings and links in mod logs

- package-lock.json
- package.json
- src/features/jobs-moderation.ts
Inexplicably dev mode was broken, so this fixes that as well
> Allow a 10 minute grace period to delete and re-post a job description

- package-lock.json
- src/features/commands.ts
Based on a recent discussion in #typescript I think it's safe to say that there's still confusion around how const works and it not being immutable.
Let me know if you want this so I can work on it
Edit: Preview of the embed on my machine
> Add initial !const command

- src/features/jobs-moderation.ts
- src/features/scheduled-messages.ts
We were stuck at 0 conversions after 15+ referrals, so we want to remove friction from the process in case that helps
> Remove 2-step referral process from Freeflow

- .github/workflows/node.js.yml
- src/helpers/env.ts
Deployment broke because I didn't update the command deploy script, and some of these env fields are optional and shouldn't shut down the process if unavailable.
> Fix env issues

- src/features/commands.ts
Updated formatting of the `!remote` message so that it looks good on Discord.
> fix: update formatting for bot

- src/features/commands.ts
Adds a canned response for users asking for recommendations for a laptop.
> Add laptop response

- src/features/emojiMod.ts
I also added a parenthetical explaining how the message got posted, to make it easier to know the feature exists
> Update variable names for brevity

- src/features/emojiMod.ts
- src/helpers/discord.ts
PR for #271
This pull request updates and simplifies the deletion validation logic for the low-effort question deleter feature.
- Compose `isStaffOrHelpful` utility function.
- Simplify and update the deletion validation logic; the criteria is now:
- At least two staff or helpful users have reacted.
- The message is not in a thread.
- Enable the feature again.
> Feature/#271: Simplify, update and enable the low-effort question remover feature

- src/features/commands.ts
> update !learn to point to official docs

- .github/workflows/node.js.yml
- TODO
- package.json
I broke something while migrating how Discord commands get deployed, subtleties of behavior abound!
> Hotfix deployment

- package-lock.json
- package.json
- src/features/jobs-moderation.ts
- src/features/jobs-moderation/validate.test.ts
Uses a LRU cache to reuse validation rule enforcement threads, and deletes the threads when they're purged from the cache. Hooray for not leaving trailing garbage around!
> Use existing job board threads if someone keeps posting

- src/features/jobs-moderation.ts
- src/features/jobs-moderation/job-mod-helpers.ts
- src/features/jobs-moderation/parse-content.test.ts
- src/features/jobs-moderation/parse-content.ts
- src/features/jobs-moderation/validate.ts
- src/features/scheduled-messages.ts
- src/helpers/modLog.ts
- src/helpers/schedule.ts
* Validate and remove messages that are edited in violation of the rules
* Don't pull in to private threads other users who were mentioned in deleted messages
* Don't run full validation on `hiring` posts. Only requires that they have valid tags
* Remove expired posts every hour, which should fix post expiration. That's not been consistently happening so far.
> Job board – edits, mentions, expiration

- src/features/jobs-moderation.ts
- src/features/jobs-moderation/validation-messages.ts
Inverted comparison, ugh. Improve validation experience while we're at it.
> Last hotfix was too hot

- src/features/jobs-moderation/job-mod-helpers.ts
- src/helpers/modLog.ts
We've had a consistent hourly error log for a few days, I added a try/catch to see if that's blowing up the rest of the log. I'm going to slam this through because job board enforcement has stopped and I'm not sure why
> Small job board fixes

- src/features/commands.ts
Hi there, 
I noticed some formatting in the `!jwt` command didn't come out quite well on the Reactiflux Discord. I decided to take a shot at improving it. This is my first contribution here so I hope I didn't miss anything essential. 
- updates/enhances formatting
- changes links to hyperlinks
> update formatting jwt command

- src/features/emojiMod.ts
- src/features/promotion-threads.ts
- src/features/stats.ts
- src/helpers/discord.ts
- src/helpers/sets.ts
- src/index.ts
- Ignore all system messages in message handler abstraction
- Use existing thread if available in "low quality question" handler
- Fix an errant console.log
- Remove a long-deprecated command
> Small fixes to longstanding minor issues

- .github/workflows/node.js.yml
- Dockerfile
- package-lock.json
- package.json
[Node 16 is dead](https://nodejs.org/en/blog/announcements/nodejs16-eol) and we need to upgrade for support and security (OpenSSL is no longer supported). In the past we seemed to use the latest Node version, so I'm upgrading to that for now.
I don't have Docker locally but everything seems to be fine on Node 20.6.1.
> Upgrade Node for security

- src/features/commands.ts
I saw this when I used the command recently.
> Pluralize sessions

- .gitignore
- src/features/commands.ts
**Feature**
`!frameworks/!framework` command to display an embed of all the popular frontend, backend, meta & non-js http frameworks that exist.
**Issue**
#337
> Feature/frameworks command #337

- src/index.ts
> reactibot-modlogs-and-debug-events

- src/features/resume-review.ts
- src/features/resume.ts
> Fix UX bugs in new Resume Review interactions

- src/features/jobs-moderation.ts
> Ensure the bot doesn't reply in separate private threads

- src/features/commands.ts
> !cra added

- package-lock.json
- package.json
- src/features/scheduled-messages.ts
This is getting moved into its own repo with a different execution environment (https://github.com/reactiflux/feeds, running on vcarl's home computer)
> Remove reddit auto-post

- src/features/book-list.ts
- src/features/debug-events.ts
- src/features/jobs-moderation.ts
- src/helpers/deploy-commands.ts
- src/helpers/discord.ts
- src/helpers/og-tags.ts
- src/index.ts
This copies the list of recommended books from the website and makes them available to link from a slash command
> Book list command
