reactiflux/reactibot

features/wit-invite.js
index.js

`!add @mention1 @mention2` should work. It's limited to people who have the role _and_ to the #women-in-tech channel, which is redundant but hey. It's also a little redundant that it's set up as a separate listener on that specific channel ID and also checks that the message came from that channel.

Add women-in-tech inviter

---

features/commands.js

Adds the "state updates may be async" command, for users who
get a *little* confused about the implications from it.
Fixes #24

feat(commands): add state updates may be async command

---

features/emojiMod.js
features/jobs.js
index.js
package-lock.json
package.json

⚠️ is for staff to log warnings for a user and their specific message
👎 is for the community to ping the moderators once a threshold (2 currently) is met

Add support for ⚠and 👎emoji moderation

---

features/commands.js

The example is too generic to be useful and doesn't have an actionable question, meanwhile the code help isn't as detailed as `!code` and is just taking up extra space

Shorten the description of !ask

---

Dockerfile
package-lock.json

This is a similar idea to #35 but using the same version of discord.js that the bot is currently using.
I copied the package-lock.json directly from the server to prevent interruptions, though it's using a slightly older version of npm (6.11.3). If the lockfile becomes too inconsistent we may need to update the server's npm version.

Add package lock

---

features/jobs.js
features/stats.js
index.js

Fixes various crashes and bugs related to changes in the discord.js API:
- Fixes bot crash when staff members use the jobs channel (major cause of recent bot downtime)
- The logged name of the server is no longer undefined
- Fixed formatting on analytics objects sent to Amplitude

Fix discord.js usage

---

src/features/commands.ts
src/features/qna.ts

Looks like Discord's API changed or something or another and `msg.guild` is undefined for a DM, so this fixes that.
I tested with my local bot and it works.

Allow commands to be DM'd to the bot

---

src/features/commands.ts

The current Code Sandbox link goes directly to the JavaScript React template. This now goes to the template page so users have the option of using TypeScript, not using React, adding a backend, etc.

Link to generic "Create Sandbox" page

---

src/features/commands.ts

Changes the title of the xy issue command to be a more relevant
title, reducing confusion when an end-user is reading the bot
response.

fix(xy): change to more apppropriate title

---

package-lock.json
package.json

We're still using a development build of discord.js, but this has since had stable releases, so we should switch to the latest stable. I've tested things out both with the TypeScript build and test server, and everything seems to be working normally.

Use stable discord.js

---

CONTRIBUTING.md
src/features/emojiMod.ts
src/utils.ts

- fix #78 
- Added a very handholdy contributing.md to set up the bot

DM members who receive a ⚠️ warning from moderators

---

src/features/commands.ts

This PR:
- Rewrites the generation of the "commands list" message so that:
- Commands are grouped into categories ("Reactiflux", "Communication", "Web", and "React/Redux")
- The message is a rich embed instead of monospace text
- The commands themselves are formatted for emphasis
- Cleans up the wording of some existing messages
- Adds two new commands:
- `!reactts`: Links to the React TypeScript Cheatsheet and warns against using `React.FC`
- `!hooks`: Links to the official React hooks docs, the `reactwithhooks.netlify.app` docs port, and the "Why Hooks?" post
Tested against Reactibutt.
New commands list:
React+TS message:
Hooks message:

Improve commands list formatting and add new "TS" and "hooks" messages

---

src/features/commands.ts

If a user already has a GitHub repo published, they can use CodeSandbox's GitHub integration to directly import their project into CSB, without having to copy/paste their code into a new CSB. This patch adds a small blurb to the `!code` command to demonstrate the usage.

add CSB github repo linking to !code command

---

src/features/commands.ts

Looks like MDN's search API behavior changed, so using the slug field to build an MDN article path is no longer sufficient (slugs are missing /docs prefix). As a fix, use the mdn_url field from the search API response instead, which seems more like what we need.

Switch !mdn to use mdn_url response field instead of slugs

---

src/features/emojiMod.ts

This does more harm than good until we can get an actual "log-in-#mod-log-but-not-DM-user" reaction.

Remove DM after warning

---

src/features/commands.ts

Add a !nw or !notworking command to politely disabuse people from simply
saying "HELP" or "This isn't working"

Add !nw command

---

src/features/emojiMod.ts

We silently ignore ⚠️ reactions if they aren't from staff, which can make it hard for the user to tell if they've done anything or not.  This changes the logic to remove the ⚠️ reaction and DM the user explaining why it was removed.
(We talked about counting ⚠️ reactions from staff as if they were 👎, but is simpler to implement and I think ultimately clearer in result)

Prevent non-staff from reacting with ⚠️ and send a clarifying DM

---

src/features/emojiMod.ts

These were incorrectly triggering "dedupe" logic, which meant multiple thumbs downs would trigger separate warnings (pinging mods each time). I removed the cleanup, which is equivalent to what we had before. This means it slowly leaks memory, but it grows with each logged warning so that's not going to be a major problem.
I also added user ID to the hashed message used to dedupe warnings, so if multiple users send the same message it won't count them as duplicates.

Fix modlog 👎 triggers

---

src/helpers/misc.ts
src/index.ts

* Allow arrays of channel IDs/handlers in `addHandler`
* Rename `duration` -> `seconds` in `sleep()`, for clearer intelligence
* Use `CHANNELS.jobBoard` instead of string id
(This is a stacked diff off #145)

Small refactors

---

.github/workflows/node.js.yml

This should resolve an issue we just encountered where merging a second PR before the first build finished caused 2 instances of the bots to be left running. This is speculative, cuz actions are annoying to test
As 1 "build and run" step, I suspect that the cancellation won't have an opportunity to interrupt. By splitting it up, it increases the odds that we'll be able to abort on duplicate merges
Uses https://github.com/marketplace/actions/cancel-workflow-action

Cancel old builds

---

src/constants.ts
src/features/autothread.ts
src/helpers/discord.ts
src/helpers/misc.ts
src/index.ts

This partially addresses the points in #134. It doesn't support timed closing, messaging to the thread on close, or adding a `!close` command, but it does enforce that threads must be used in a specific channel!
The rules:
* Top-level messages will have threads created with the name `name – time date`
* Replies to the message are deleted, with the messaged DM'd to the sender
* Replies to your own messages are _not_ removed (they stick around), intended to allow "followup" questions to be linked together
Video preview:
https://user-images.githubusercontent.com/1551487/147841572-bbd8362a-3ea8-45f3-a4d5-ea2c57c77db2.mov
(This is a stacked diff off #146)

Add support for thread-only channels

---

src/features/emojiMod.ts

Also some small refactors. I just can't help myself.
* Kick instead of banning users reported for spam. This reduces our mod burden, cuz folks who get compromised can rejoin after locking down their account again. Since we already delete these messages, it won't matter if they continually join and spam, cuz it won't be seen by most members. If spammers start getting around our deletion, we might need to reconsider
* Fix a bug where spam reports don't update the warning to display number of reports
* Change `handleReport` to return the number of warnings, which let me…
* Move "auto kick" logic out of handleReport and into the spam emoji handler

Kick spammers instead of banning

---

src/features/stats.ts

Going to merge this quickly because it affects data collection.
Our "channel activity" dashboards are showing `#help-js` at ~ 0 activity, since the channel id being tracked is from the thread. That's not helpful, so use the parent channel id.

Use parent channel id for metrics on messages sent in threads

---

src/constants.ts
src/features/autothread.ts

This posts an instructional message at the start of every thread, then deletes it after 30 seconds
> React to someone with ✅ to mark their response as the accepted answer and close this thread

Give a short-lived instruction at the start of every thread

---

src/constants.ts
src/features/autothread.ts
src/features/emojiMod.ts
src/features/stats.ts
src/helpers/discord.ts

* Emit metrics so we can track activity
* Allow members with helpful roles + staff to mark questions as answered
* Don't lock threads when answers are marked
* Share links to "how to ask good questions" resources if the thread was closed without any messages

Improve auto thread experience

---

src/features/autodelete-spam.ts
src/features/autothread.ts
src/features/commands.ts
src/features/emojiMod.ts
src/helpers/modLog.ts

* Remove "discord" as a trigger word, too common
* Change to a spam score method of responding, not a boolean
* Consolidate `@everyone` handlers into 1 spot. I think this resolves the "Unknown Message" logs we've had in #bot-log

Revise spam handling

---

src/features/emojiMod.ts

We've had some flaky handling for ⚠️ reactions lately, it looks like it comes down to whether the message was sent before or after the bot was restarted because the message author wouldn't be cached. By always fetching the author, it should be more reliable

Fix flaky reaction handling by always fetching message author

---

src/features/commands.ts

I find that it is a useful reminder when users are being inappropriate to remind them (or inform them) of the server's Code of Conduct. When doing so I usually have to open a new tab and search for it. It would be useful to have it as a command so that it can be easily accessible and more often remind users about them.

added Code of Conduct command

---

src/features/commands.ts

Similar to the `!conduct` command, this will add the `!promotion` command to remind users of the guidelines around self-promotion. I saw the need for it in this message:

added self-promotion guidelines command

---

src/features/commands.ts

This PR:
- Adds the Reactiflux "Learning Resources" link to the `!learn` command
- Removes the `!reduxvscontext` command, because that also accidentally triggers `!redux`.  (The message still works with `!context`
- Reorders the links for the `!context` command to put "Context isn't State Management" first

Add 'Learning Resources' link and fix Context command

---

.github/workflows/node.js.yml
Dockerfile
src/constants.ts
src/constants/channels.ts
src/features/autothread.ts
src/features/emojiMod.ts
src/features/jobs-moderation.ts
src/features/scheduled-messages.ts
src/helpers/env.ts
src/index.ts

Also a couple of small fixes:
* Move stop/clean docker commands so there isn't a delay of few seconds where the bot isn't running
* Fix docker build to include `yarn.lock`
* Use `CHANNELS.botLog` instead of loading it from an environment variable

Add env detection to switch channel constants automatically

---

src/features/commands.ts

"Lifting state up" was renamed in the new docs to "Sharing state between components" - https://beta.reactjs.org/learn/sharing-state-between-components - the spirit of the doc page is the same and I believe people here remember the `!lift` command, so I wouldn't change the command itself, just the link to the doc page.
Discussed in https://discord.com/channels/102860784329052160/955495969628233748

Update !lift link to new docs

---

.github/workflows/node.js.yml
package.json
scripts/deploy-commands.ts
src/helpers/sets.ts
tsconfig.json
yarn.lock

I talked with Nick about this a little bit a few weeks ago, #148 looked like it hit a wall due to how weirdly different slash commands are from responding to messages. There's still a larger change we could make for performance reasons if we need it (we won't need it) where we could set up a web server, and configure Discord to emit web hooks for commands instead of using a persistent network connection.
The meat of this change is in `scripts/deploy-commands.ts`, which fetches the commands and compares the remote list with its local list. This requires that we update the deployment script for every new command we add, but that should be a pretty small amount — command arguments allow us to do most things we are currently, so for example we can do 1 command instead of like 15 for our saved …

Deploy Discord commands during bot build

---

.github/workflows/node.js.yml
scripts/deploy-commands.ts
src/commands/report.ts
src/constants.ts
src/features/commands.ts
src/features/emojiMod.ts
src/helpers/modLog.ts
src/index.ts

Currently, moderators can use a ⚠️ reaction to log a message and MVPs/other members can use 👎 to report inappropriate messages, but both of these expose the name of the user who reacted.
This builds on support for Application Commands (#198) to add an option to any message's context menu, allowing it to be reported entirely anonymously.
I opted not to track the name of who reported in #mod-log, since it's advertised as "anonymously report". We can reconsider if it's a problem.

Add anonymous message reporting mechanism

---

.dockerignore
.github/workflows/node.js.yml
Dockerfile

Our "build" step is currently redundant, it installs/builds/tests, which allows the deployment step to install/build/run. If we uploaded docker images as a build artifact from this CI step, we could reuse it when deploying code.
I want to make that transition in several parts:
* (this PR) swap out "build" step to use docker and add ability to upload docker images (currently disabled as its unused)
* swap out deploy step to use the docker image built from CI
* (stretch) reduce custom deploy code and use more powerful build primitives. We're SSHing into a DO Droplet and running some commands directly on the server. DO exposes a managed Kubernetes product that looks pretty cheap and simple — if we could replace "ssh into a server and run docker" with "stand up a new k8s deployment," that …

Run CI build with Docker

---

src/commands/report.ts
src/constants.ts
src/features/emojiMod.ts
src/features/jobs-moderation.ts
src/helpers/modLog.ts

Previously all removed posts were displayed with a bare ping + timestamp, now they'll have a reason as well.
old:
```
@vcarl's test account’s job post from 05/17/2022 4:10 PM was deleted
```
new:
```
@vcarl's test account in job-board warned 1 times, post was deleted:
Originally sent 05/17/2022 4:13 PM
`[hiring] butts`
```
```
@vcarl's test account in job-board warned 1 times, account too young:
[hiring] butts
```
```
@vcarl's test account in job-board warned 1 times, posting too frequently:
[hiring] butts
```

Improve mod logs when job board automod reacts

---

src/helpers/discord.ts
src/helpers/modLog.ts

`#mod-log` escapes messages with \` around messages, but this breaks unpleasantly on code samples. This change properly escapes backticks so they render as plain text and inserts `> ` on each line so it renders as a quote

Fix quoting of reported messages

---

src/features/jobs-moderation.ts

I've noticed from mod logs that we seem to be catching up way more legitimate accounts than scammers with the account age filter. I've noted that the NFT posters I end up banning have figured out the delay, and a fair number of legitimate posters don't return. 
So, let's tune this wayyy down. 1 hour should be sufficient to encourage them to poke around the server without being so long that they completely forget

Tune down account age requirements from 3d to 1hr

---

src/features/promotion-threads.ts

Some were failing to create a thread because the title was over the 100 char cutoff.

Fix promotion thread titles

---

src/constants/channels.ts
src/features/jobs-moderation.ts
src/helpers/modLog.ts
src/index.ts

Iggy brought up that we're getting a ton of noise from the job board logging now, and it's clogging up the rest of the moderation and making us more likely to miss reports. Moving these logs into a separate channel will help us stay focused

Move job board mod logs into a separate channel

---

src/features/jobs-moderation.ts
src/helpers/modLog.ts

Cryptocurrency and blockchain isn't the main focus of the community, and we've had a lot of issues with moderating job postings from members who want to share from these topics. [Freeflow](https://freeflow.dev) reached out to suggest that we refer these posters over to them, which is a great win/win — we can automatically remove all these posters, and the posters get a high-quality channel where they can promote themselves.
There are separate paths for employers and developers, which we attempt to infer automatically from the tags they use. If no tags were used, then we offer both paths.
User flow:
* Member posts with a trigger word (blockchain, nft, cryptocurrency, token, web3)
* Post is removed, and a reply sent with a button
* Upon button click, log privately the member and send a …

 Block all cryptocurrency/nft/blockchain job postings

---

src/features/commands.ts

MDN  have changed the structure of their api, moving the locale from being a url parameter to being a query parameter.
Have tested on private server with reactibot

Updating the mdn url to match the new api structure to fix the mdn bot

---

src/features/commands.ts

A lot of folks have been asking for help with acquiring remote jobs over the years, especially recently. This PR adds a command to the bot that allows a user to use either `!remote` or `!remotework` to view links related to this subject.
Given the relatively high number of junior developers asking about remote work, I've included a note section warning folks at this stage of their career that acquiring a remote job is incredibly rare. I have opted to do so given that this is generally stated by many who reply to this question on the Reactiflux server to optimize the amount of time saved.

Feat: Adds remote work command to bot

---

src/features/commands.ts

One of the links in the `!remote` command has had a change in ownership since the time it had been pinned in Reactiflux originally. This PR removes that bad link.
Apologies for not realizing sooner.

fix: remove link due to change in domain ownership

---

src/features/jobs-moderation.ts

This adds a new system to track the user ID of anyone who posts a crypto job, and prevents them from sharing more job posts. If they continue to post (like if they’re trying to circumvent the filter), they’ll be timed out for 20 hours to prevent them posting.
Closes #257

More aggressively block crypto job posters

---

src/features/commands.ts

PR for #259
This pull request prepends "Please don't post code in screenshots. Instead, use one of these:" to the `!code` command output to suggest against posting screenshots of code.
- Update `!code` command output.
- I've altered the formatting of the command description slightly to start the content of the message on a new line to aid readability, in my opinion. Please let me know if this isn't preferred.

Feature/#259: Prepend message to suggest against code screenshots to the `!code` command output

---

src/features/commands.ts

PR for #262
This pull request adds a `!keys` command that explains the importance of keys when rendering lists in React. It also references two authoritative resources with further information.
- Add `!keys` command.

Feature/#262: Add command to explain the importance of keys when rendering lists in React

---

src/features/commands.ts

Removes a link to an old post to be updated with a more reliable source (old post will most likely be deleted soon).

chore(commands): update state update command links

---

src/features/jobs-moderation.ts

As the board has shifted, this has been less of an effective defense against spammers, than a point of friction for legitimate posters. Begone, delay!

Remove time delay after joining to post a job

---

src/features/autothread.ts
src/features/emojiMod.ts
src/helpers/modLog.ts
src/helpers/threads.ts

PR for #271 
This pull request implements the bot feature that removes low-effort questions, educates the authors, and encourages them to ask more reasonable questions.
The feature:
- Creates a new thread from the offending message.
- Sends an educative and encouraging message to the thread to help the user improve their question (thanks @vcarl!).
- Deletes the offending message to clean up the channel.
- Logs the deletion in the moderation log.
- Create and consume a shared utility function to create new thread names (I did this before changing the thread name/format subsequently but decided to leave it in).
- Extend the emoji moderation feature to include a reaction handler for low-effort questions.
- Extend the report log to support low-effort question removal logs.
- ~I'm leaving the …

Feature/#271: Write low effort question remover feature

---

src/features/emojiMod.ts

PR for #271 
This pull request temporarily disables the low-effort question remover feature whilst we clarify and update the deletion validation logic.

Feature/#271: Temporarily disable low-effort question remover feature

---

src/features/commands.ts

PR for #285.
This pull request updates the React website and documentation links referenced by commands as the React team has promoted the new (previously beta) website and documentation.
- Update references to the previously beta (now live) React website and documentation.
- Update references to the previously live (now legacy) website and documentation.

Feature/#285: Update React website and documentation links referenced by commands

---

src/features/jobs-moderation.ts
src/features/jobs-moderation/job-mod-helpers.ts
src/features/jobs-moderation/validate.ts
src/helpers/string.test.ts
src/helpers/string.ts

* Fix some control characters being interpreted as emoji
* Improve error message when there are too many newlines
* Loosen length restrictions on FORHIRE posts
* Don't run typical validation against staff accounts

Quick adjustments to job moderation

---

src/features/jobs-moderation.ts
src/features/jobs-moderation/job-mod-helpers.ts

Found 2 critical bugs:
- `deleteAgedPosts` was incorrectly operating on the full list of posts, not just `forhire` posts
- The interval was incorrectly set at 1.25 hours, not 1.25 days.
This also should fix a bug where `message.fetch()` on old messages that aren't in the message cache are emitting `messageCreate` events (I think? It's not documented anywhere)

Job board – Hotfix some high priority fixes

---

src/features/jobs-moderation/job-mod-helpers.ts

I'm growing suspicious that we may have been flagged by Discord's systems for quirky bot behavior, trying to fetch/delete old messages (or something). Testing locally and this still works same as ever, so either there's something specific about the real server's job board, or something quirky with the application ID in Discord's systems. But anyway this is def a bug

One more job board patch

---

src/features/jobs-moderation/job-mod-helpers.ts

Probably more fixes to come, but this should stop it from blowing up as badly as it has been. Don't need to flood #bot-log

Another job board hot fix

---

src/features/jobs-moderation/job-mod-helpers.ts
src/features/jobs-moderation/validate.ts

This should fix the issue we've been seeing with crashes on invalid messages. Specifically the issue was because the array that was being `shift`ed was not the same one being iterated on, thus the infinite loop.
Now the shift is a) done on the correct array, b) performed immediately after getting a reference to the underlying message, which should resolve the infinite loops we've been experiencing
We'll see if this also fixes the incorrect behavior I've seen where old forhire posts aren't reliably cleared out.

Hopefully final fix to infinite loop bug

---

src/features/commands.ts

- edits formatting of the `!context` embed contents to look better on mobile
- changes the links into a list of links in descriptive format
(edit: apologies for the former PR edits/commits to show up, hope you can squash them away :))

Update !context bot command formatting and add descriptive (hyper-)links

---

src/features/stats.ts
src/helpers/discord.ts
src/helpers/sets.ts

The Star Helper admin work has shown me that we could more effectively use our metrics to drive activity-based segments of the community if we can segment activity by channel group, i.e. by asking for a chart of the top 25 posters by message volume in the "Need Help" channel category, vs pulling out individual channel IDs to build the same chart.
Similarly, we could use channel tags to monitor usage of different tags. Right now we don't make much use of forums, but we're exploring a change to help channels that would more strongly emphasize them.

Update metrics: track forum post tags, message channel category

---

src/features/commands.ts

A small change to create a descriptive hyperlink in the output of this command. Both the current version and the updated version are shown below respectively.

update: !conduct command. Change the CoC link to a descriptive hyperlink

---

src/features/commands.ts

A minor change to create a descriptive hyperlink in the output of this command `!promotion`. Both the current version and the updated version are shown below respectively.

update !promotion command with a hyperlink

---

src/features/commands.ts

A minor edit to include the link as a descriptive hyperlink
Both the current and PR version output are shown below respectively.

update !rrlinks link to descriptive hyperlink

---

src/features/emojiMod.ts
src/features/jobs-moderation.ts
src/features/jobs-moderation/job-mod-helpers.ts
src/features/jobs-moderation/validate.ts
src/features/jobs-moderation/validation-messages.ts
src/helpers/array.test.ts
src/helpers/array.ts
src/helpers/discord.ts
src/helpers/modLog.ts
src/helpers/string.test.ts
src/helpers/string.ts

- #312 Don't re-validate `hiring` posts if they're edited, so they never get removed
- #313 Log pre- and post-edit messages, so we can spot-check for accidents or nefarious activity
- #314 Fix line count validation and typo
- #316 Change "low effort question" thread to be private
- Fixes a bug in `partition()` where documented behavior didn't match code

Job board line count, edit tracking, edited hiring posts. Low effort questions

---

src/features/commands.ts

Hi there, I had a little time to edit a few commands. I fixed a typo here and there and converted the links to hyperlinks. 
Commands changed:
- `!xy`
- `!ymnnr`
- `!derived`
- `!su`
- `!bind`
- `!lift`
- `!ask`
Results:

update a few bot command outputs to use (descriptive) hyperlinks

---

src/features/jobs-moderation.ts
src/features/jobs-moderation/job-mod-helpers.ts
src/features/jobs-moderation/validate.test.ts
src/features/jobs-moderation/validate.ts
src/features/jobs-moderation/validation-messages.ts
src/helpers/env.ts
src/types/jobs-moderation.ts

* Require links in HIRING posts
* Double the lifespan of a FORHIRE post to 60 hours
* Don't delete edited messages. If we hit problems with formatting evasion, we'll need to reevaluate. Edited posts still get flagged, just not deleted.
* Small copy adjustments on validation failure thread creation
* Small adjustments to support test environment

Adjust jobs moderation bot

---

src/features/voice-activity.ts
src/index.ts
src/types/index.ts

Does what it says on the box. It needs a new intent but afaict the bot itself doesn't need to be updated for that? Idk how intents work.

Add voice activity tracking

---

src/features/voice-activity.ts
src/index.ts

Simplify formatting for voice channel logs

---

src/features/commands.ts
src/helpers/react-docs.ts

Implemented additional commands `!docs` and `!react-docs` to search React documentation. The output embed will contain a link to documentation and short intro segment from their page.
Extra:
- Fixed MDN `icon_url` not being found.

Implement search React documentation command #348

---

src/features/commands.ts

Run prettier to resolve `test:lint` failing on CI.

Run prettier to resolve build issues on main branch

---

src/features/commands.ts
src/helpers/react-docs.test.ts
src/helpers/react-docs.ts

fix: react documentation commands can not be in sentence #354

---

src/features/emojiMod.ts
src/features/log.ts
src/features/resume.ts
src/features/retry.ts
src/features/scheduled-messages.ts

Fixes #382 by adding a `retry()` helper and wrapping the `fetchStarterMessage` call.
Fixes #358 by extending the existing filter call to check IDs
Improves but leaves #380 open by linking to channels correctly
Fixes an issue where AI resume review sometimes wouldn't log because it was too long, by truncating output in the channel log helper
Improves our logging for resume feedback by linking to the source thread for the log

Improvements to logs, fix crash in resume review, experience polish

---

src/features/resume-review.ts

Resolve issue where Reactibot would send cooldown message to occurring messages without attachments, when user has cooldown for pdf generation.

fix: reactibot do not send cooldown message without attachment

---

src/features/mod-activity.ts

make sure timeout events dont fire on historical timeouts

timeout-logs-tweaks

---

src/features/resume.ts

Fixes issue when `this` is `undefined` when we have destructed the `fetchStarterMessage`.
```js
[ERROR] Cannot read properties of undefined (reading 'parent') TypeError: Cannot read properties of undefined (reading 'parent')
at fetchStarterMessage (/build/reactibot/node_modules/discord.js/src/structures/ThreadChannel.js:315:26)
```

fix: this context lost on destruct

---

package-lock.json
package.json
src/features/commands.ts
src/features/jobs-moderation.ts
src/features/promotion-threads.ts
src/features/resume.ts
src/helpers/discord.ts
src/helpers/react-docs.ts
tsconfig.json

- Updated dependencies and Typescript version.
Some of the libraries e.g `querystring`, `node-fetch` are not updated as it would require to use dynamic import. We should probably just move away from `commonjs` module.
Closes #357

#357 deps: upgrade dependencies and Typescript versions

---

package-lock.json
package.json
src/features/commands.ts

The list of items is open for discussion. Feel free to comment, add, update, or remove some of the items.
I added [`dedent`](https://www.npmjs.com/package/dedent) for better DX. Please let me know if you prefer not to do this in this PR, or use `dedent` to all other commands at once.

feat(commands): add a command for a list of "good to know" items for job applications, particularly juniors

---

src/features/resume.ts
src/features/retry.ts

Add additional error logging for the resume feature and handle retrying the firstMessage when thread has been created

fix: add error logging and retry to threadCreate resume

---

package-lock.json
package.json
src/features/scheduled-messages.ts

Only shows a maximum of 5 posts, and only posts that meet this filter:
```js
post.ups - post.downs >= 10 &&
countLines(post.selftext) <= 15 &&
post.selftext.length < 2000 &&
post.upvote_ratio > 0.65,
```
So, > 10 points, < 15 lines of text, under 2k characters, and 65% upvoted. This should keep it from overwhelming the channel, but I've caught some solid resources coming through in Reddit so I thought this would be good. Resolves #389

Share top posts from /r/reactjs every night at midnight

---

src/features/commands.ts

Added command `!auth` to show authentication resources, additionally you can add a user to the reply as such and the user will be apart of the embed:
**Example reply from bot**

feature: added command !auth solves #398

---

src/features/commands.ts
src/features/mdn.ts
src/index.ts

This lets autocomplete function as a search field, so folks can make sure they're sending what they mean to

Complement !mdn with /mdn

---

src/helpers/react-docs.ts

Updated React documentation to version 19.
**Extra notes:**
- Allow trailing dot (.) for the search term.
- Replace double empty-blank lines for the content to single line.
Closes #422.

#422 Update React docs to v19

---

src/features/jobs-moderation.ts
src/features/jobs-moderation/job-mod-helpers.ts
src/features/jobs-moderation/parse-content.test.ts
src/features/jobs-moderation/parse-content.ts
src/features/jobs-moderation/validate.test.ts
src/features/jobs-moderation/validate.ts
src/features/jobs-moderation/validation-messages.ts
src/index.ts
src/types/jobs-moderation.ts

- Correctly post "you're good!" message in REPL thread
- Correctly respond to edited messages that do not comply with formatting rules (and allow repost if recent)
- Stop job validation from chiming in on irrelevant threads
- Correctly parse posts in the format of `[for hire] im a developer`
This is a rehash of #428 because of some showstopper bugs

Fix a couple of long-standing bugs in job board validation logic

---

.git-blame-ignore-revs
README.md
cluster/ingress.yaml
cluster/service.yaml
kustomization.yaml
src/features/jobs-moderation/job-mod-helpers.ts
src/index.ts
src/server.ts

This might need some tweaking but I'm pushing up a solid first effort
I'll need to ship some DNS changes before this merges
Refresh of #427 because whoops it was hella broken. Had to ship #431 separately first

Add an API for active job posts

---

src/helpers/string.ts
src/server.ts

I spotted a weirdo formatted post that used spaces to emulate bullet points, which is bananas, but it also broke the  markdown formatter. Discord doesn't support the 4-spaces-for-code markdown format, so this is fine.

Compress 3 spaces down to 2

---

CONTRIBUTING.md

also improved some sentences clarity

docs: updated the contributing page due to additional discord bot set up

---

package-lock.json
package.json
src/features/commands.ts
src/features/emojiMod.ts
src/helpers/string.ts
test/commands.test.ts

I have tried to fix the issue #412  that is text in code block as comments. 
The code I have used to fix this is Attached below - 
```
// Helper functions to handle commands inside codeblocks
export function removeCodeBlocksAndQuotes(text: string): string {
if (!text) return '';
let filtered = text.replace(/```[\s\S]*?```/g, '');
filtered = filtered.replace(/`[^`]+`/g, '');
filtered = filtered.replace(/^>.*$/gm, '');
filtered = filtered.replace(/>>>[\s\S]*?(?=\n\n|$)/g, '');
filtered = filtered.replace(/\n{3,}/g, '\n\n').trim();
return filtered;
}
export function isInsideCodeBlock(text: string, position: number): boolean {
// Count backticks before position
const beforeText = text.slice(0, position);
const singleBackticks = (beforeText.match(/`/g) || []).length;
const tripleBackticks = …
```

Exclude code blocks when looking for !command triggers - Fixes #412

---

src/features/commands.ts

This pull-request resolves #460 for adding a cross-post command. Below is a preview of the command.

add: cross post command

---

src/features/commands.ts
src/index.ts

This pull-request resolves #452 
I have attached a preview of the command.

add: contribution command

---

src/features/job-scanner.ts

**description**: Added edge case to disable job scanner bot for admins/mods due to certain keywords like DM me that make the bot trigger for mods/admins. This is the same helper edge case used for job moderations.

update: disabled job scanner for admins/mods

---

src/features/emojiMod.ts

**Description**: This pull request resolves #449 by adding more descriptive logging for emojiMod.ts to trace the cause of this error.

update: added descriptive logging for Unknown Member DiscordAPIError.

---

src/features/job-scanner.ts

**description**:
- Disabled job scanner bot for Star Helpers and other helpful roles.
- Added better error logging as there have been cases where an auto reply message is not getting deleted after X seconds. And to log details about the deleted message for more insights on how this feature is doing.
- Changed auto reply deletion time from 5 minutes to 30 seconds.

chore: improve error logging, edge case handling, and timeout delay
